version: '3'
services:
   db:
     image: mysql:5.7
     ports:
       - "3306:3306"
     volumes:
       - ~/db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: Admin123
       MYSQL_DATABASE: wordpress
       MYSQL_USER: tecnico
       MYSQL_PASSWORD: 12345

volumes:
    db_data:
networks:
    work:
      - bridge
